# Generated by Django 4.0.6 on 2022-07-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='xona',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
